import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./_styles/globals.css"
import RootContext from "./_context/root-context"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootContext>{children}</RootContext>
      </body>
    </html>
  )
}
