import type { Metadata } from "next"
import RootContext from "./_context/root-context"

import { cn } from "./_lib/utils"
import "./globals.css"
import authApi from "./_api/auth"
import NeedLogin from "./_components/layout/need-login"
import Header from "./_components/layout/header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const authCheck = await authApi.getAdminAuthCheck()

  return (
    <html lang="ko">
      <body className={cn("min-h-screen bg-[#E0E5F7]")}>
        <Header />

        <RootContext>{children}</RootContext>
      </body>
    </html>
  )
}
