# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
# TODO: on - pr, path
name: pr:db:production:migration
on:
  # pull_request_review:
  #   types: [submitted]
  push:
    branches:
      - add/release-*
    # paths:
    #   - 'packages/kysely-schema/**'

jobs:
  migrate:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      -
        name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.0.0'
      -
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      -
        name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      -
        uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      -
        name: Install dependencies
        run: pnpm install -r --frozen-lockfile
      # deploy packages/kysely-schema
      -
        name: Deploy packages/kysely-schema
        run: pnpm deploy --filter ./packages/kysely-schema ./prod/packages/kysely-schema
      # short SHA commit for docker image tag
      - name: Get commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # create docker image
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_MIGRATOR_TAG }}:latest, ${{ secrets.DOCKERHUB_MIGRATOR_TAG }}:${{ env.SHORT_SHA }}
          target: packages_kysely-schema
          platforms: linux/amd64
      # run docker image on remote env
      -
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: ${{ secrets.SSH_CMD_MIGRATE }}
