# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: pr:db:production:migration
on:
  push:
    branches: [main]
    paths:
      - 'packages/kysely-schema/**'

jobs:
  migrate-production-db:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      # short SHA commit for docker image tag
      - name: Get commit SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # create docker image
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          tags: ${{ secrets.DOCKERHUB_MIGRATOR_TAG }}:latest, ${{ secrets.DOCKERHUB_MIGRATOR_TAG }}:${{ env.SHORT_SHA }}
          target: backend_service
          platforms: linux/amd64
      # run docker image on remote env
      -
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: ${{ secrets.SSH_CMD_MIGRATE }}
